<a href="https://colab.research.google.com/github/darshank26/Linear_Algebra_for_ML/blob/main/011_tensor_reduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Tensor Reduction using numpy

Calculating all the elements across the tensors is known as Tensor reduction


In [2]:
import numpy as np


x = np.array([[12,10],[20,13],[15,14]])

x

array([[12, 10],
       [20, 13],
       [15, 14]])

In [3]:
#sum of all elements

x.sum()

84

In [4]:
#sum of elements across the axis

x.sum(axis=1)


array([22, 33, 29])

In [5]:
x.sum(axis=0)

array([47, 37])


#Tensor Reduction using pytorch



In [6]:
import torch as py


x = py.tensor([[12,10],[20,13],[15,14]])

x

tensor([[12, 10],
        [20, 13],
        [15, 14]])

In [8]:
x.sum()

tensor(84)

In [9]:
x.sum(axis=0)

tensor([47, 37])

In [10]:
x.sum(axis=1)

tensor([22, 33, 29])


#Tensor Reduction using tensorflow



In [11]:
import tensorflow as tf


x = tf.Variable([[12,10],[20,13],[15,14]])

x

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[12, 10],
       [20, 13],
       [15, 14]], dtype=int32)>

In [12]:
tf.reduce_sum(x)

<tf.Tensor: shape=(), dtype=int32, numpy=84>

In [13]:
tf.reduce_sum(x,0)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([47, 37], dtype=int32)>

In [14]:
tf.reduce_sum(x,1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([22, 33, 29], dtype=int32)>