<a href="https://colab.research.google.com/github/darshank26/Linear_Algebra_for_ML/blob/main/03_vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Vectors in Numpy

In [3]:
import numpy as np

x = np.array([10,20,30])

x

array([10, 20, 30])

In [4]:
len(x)

3

In [5]:
x.shape

(3,)

In [14]:
type(x)

numpy.ndarray

In [15]:
x[0]

10

In [16]:
type(x[0])

numpy.int64

#Vector Transposition

In [19]:
#no transposition

x_T  = x.T

x_T

array([10, 20, 30])

In [20]:
x_T.shape

(3,)

In [21]:
#here we are specifically  creating 2-D array

y_T = np.array([[10,20,30]])

y_T

array([[10, 20, 30]])

In [22]:
y_T.shape

(1, 3)

In [23]:
#now we can do transposition
y_T.T

array([[10],
       [20],
       [30]])

In [25]:
(y_T.T).shape

(3, 1)

#Zeros vector

In [28]:
x = np.zeros(3)

x

array([0., 0., 0.])

In [29]:
x.shape

(3,)

#Vectors in Pytorch

In [30]:
import torch

x_pt = torch.tensor([10,30,50])

x_pt

tensor([10, 30, 50])

In [31]:
x_pt.shape

torch.Size([3])

#Vectors in Tensor

In [33]:

import tensorflow as tf

x_tf = tf.Variable([10,20,40])

x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([10, 20, 40], dtype=int32)>

In [34]:
x_tf.shape

TensorShape([3])