<a href="https://colab.research.google.com/github/darshank26/Linear_Algebra_for_ML/blob/main/06_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrices


Matrices are rank 2 tensor

#Using numpy

In [1]:
import numpy as np


In [2]:
x = np.array([[10,20],[30,40],[50,60]])

In [5]:
x

array([[10, 20],
       [30, 40],
       [50, 60]])

In [3]:
x.shape

(3, 2)

In [4]:
x.size

6

In [7]:
x[:,0]

array([10, 30, 50])

In [8]:
x[0,:]

array([10, 20])

#Using Pytorch

In [10]:
import torch as py



In [11]:
x = py.tensor([[10,20],[30,40],[50,60]])

In [12]:
x

tensor([[10, 20],
        [30, 40],
        [50, 60]])

In [14]:
x.shape

torch.Size([3, 2])

#Using Tensor

In [16]:
import tensorflow as tf


In [17]:
x_tf = tf.Variable([[10,20],[30,40],[50,60]])
x_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[10, 20],
       [30, 40],
       [50, 60]], dtype=int32)>

In [18]:
tf.size(x_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [19]:
tf.shape(x_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>