<a href="https://colab.research.google.com/github/darshank26/Linear_Algebra_for_ML/blob/main/08_tensor_transposition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Tensor Transposition



#Transpose in Numpy

In [1]:
import numpy as np

In [7]:
x = np.array([[20,13,14,1],[90,20,40,4],[13,18,20,0]])

x

array([[20, 13, 14,  1],
       [90, 20, 40,  4],
       [13, 18, 20,  0]])

In [9]:
x.shape

(3, 4)

In [10]:
x.T

array([[20, 90, 13],
       [13, 20, 18],
       [14, 40, 20],
       [ 1,  4,  0]])

In [11]:
(x.T).shape

(4, 3)

#Transpose in Pytorch

In [15]:
import torch as py

In [16]:
x = py.tensor([[20,13,14,1],[90,20,40,4],[13,18,20,0]])

x

tensor([[20, 13, 14,  1],
        [90, 20, 40,  4],
        [13, 18, 20,  0]])

In [17]:
x.T

tensor([[20, 90, 13],
        [13, 20, 18],
        [14, 40, 20],
        [ 1,  4,  0]])

#Transpose in Tensorflow

In [18]:
import tensorflow as tf

In [19]:
x = tf.Variable([[20,13,14,1],[90,20,40,4],[13,18,20,0]])

x

<tf.Variable 'Variable:0' shape=(3, 4) dtype=int32, numpy=
array([[20, 13, 14,  1],
       [90, 20, 40,  4],
       [13, 18, 20,  0]], dtype=int32)>

In [20]:
tf.transpose(x)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[20, 90, 13],
       [13, 20, 18],
       [14, 40, 20],
       [ 1,  4,  0]], dtype=int32)>