<a href="https://colab.research.google.com/github/darshank26/Linear_Algebra_for_ML/blob/main/09_basic_tensor_arithmetic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix arithmetic using numpy

In [1]:
import numpy as np

x = np.array([[12,14,10],[20,14,15],[30,40,15]])

x

array([[12, 14, 10],
       [20, 14, 15],
       [30, 40, 15]])

In [2]:
x*3

array([[ 36,  42,  30],
       [ 60,  42,  45],
       [ 90, 120,  45]])

In [3]:
x+1

array([[22, 24, 20],
       [30, 24, 25],
       [40, 50, 25]])

In [4]:
x**3

array([[ 1728,  2744,  1000],
       [ 8000,  2744,  3375],
       [27000, 64000,  3375]])

In [5]:
x/10

array([[1.2, 1.4, 1. ],
       [2. , 1.4, 1.5],
       [3. , 4. , 1.5]])

In [6]:
x%10

array([[2, 4, 0],
       [0, 4, 5],
       [0, 0, 5]])

#Matrix arithmetic using pytorch

In [7]:
import torch as py

x = py.tensor([[12,14,10],[20,14,15],[30,40,15]])

x

tensor([[12, 14, 10],
        [20, 14, 15],
        [30, 40, 15]])

In [8]:
x*10

tensor([[120, 140, 100],
        [200, 140, 150],
        [300, 400, 150]])

In [9]:
x+20

tensor([[32, 34, 30],
        [40, 34, 35],
        [50, 60, 35]])

In [10]:
x**4

tensor([[  20736,   38416,   10000],
        [ 160000,   38416,   50625],
        [ 810000, 2560000,   50625]])

In [11]:
x/12

tensor([[1.0000, 1.1667, 0.8333],
        [1.6667, 1.1667, 1.2500],
        [2.5000, 3.3333, 1.2500]])

#Matrix arithmetic using Tensorflow

In [12]:
import tensorflow as tf

x = tf.Variable([[12,14,10],[20,14,15],[30,40,15]])

x

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[12, 14, 10],
       [20, 14, 15],
       [30, 40, 15]], dtype=int32)>

In [13]:
x*10

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[120, 140, 100],
       [200, 140, 150],
       [300, 400, 150]], dtype=int32)>

In [14]:
x+100

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[112, 114, 110],
       [120, 114, 115],
       [130, 140, 115]], dtype=int32)>

In [15]:
x-12

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 0,  2, -2],
       [ 8,  2,  3],
       [18, 28,  3]], dtype=int32)>

In [16]:
x**2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 144,  196,  100],
       [ 400,  196,  225],
       [ 900, 1600,  225]], dtype=int32)>

In [17]:
x/8

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[1.5  , 1.75 , 1.25 ],
       [2.5  , 1.75 , 1.875],
       [3.75 , 5.   , 1.875]])>