<a href="https://colab.research.google.com/github/darshank26/Linear_Algebra_for_ML/blob/main/010_hadamard_product.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Hadamard Product

the Hadamard product (also known as the element-wise product, entrywise product or Schur product) is a binary operation that takes in two matrices of the same dimensions and returns a matrix of the multiplied corresponding elements.

This operation can be thought as a "naive matrix multiplication" and is different from the matrix product

#Hadamard Product using Numpy

In [1]:
import numpy as np

A = np.array([[12,13,15],[10,20,12],[10,24,25]])

A


array([[12, 13, 15],
       [10, 20, 12],
       [10, 24, 25]])

In [2]:
B = np.array([[10,11,20],[20,10,13],[15,20,1]])
B

array([[10, 11, 20],
       [20, 10, 13],
       [15, 20,  1]])

In [3]:
A + B

array([[22, 24, 35],
       [30, 30, 25],
       [25, 44, 26]])

In [4]:
A - B

array([[  2,   2,  -5],
       [-10,  10,  -1],
       [ -5,   4,  24]])

In [5]:
A * B

array([[120, 143, 300],
       [200, 200, 156],
       [150, 480,  25]])

In [6]:
A + A - B

array([[14, 15, 10],
       [ 0, 30, 11],
       [ 5, 28, 49]])

In [7]:
A * B

array([[120, 143, 300],
       [200, 200, 156],
       [150, 480,  25]])