<a href="https://colab.research.google.com/github/darshank26/Linear_Algebra_for_ML/blob/main/12_dot_product.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Dot product of Tensors

if we have a two vectors say x and y then we can calculate the doct product of the two vector using x.y notation

#Using numpy

In [5]:
# dot product using one d array

import numpy as np

A = np.array([1,2,3])

B = np.array([2,2,2])


np.dot(A,B)

12

In [11]:
# dot product using 2 d array

import numpy as np

A = np.array([[1,2,3],[4,5,6]])

B = np.array([[2,2,2],[3,3,3]])

# make a transposition of vector B for dot product

A.shape

(2, 3)

In [12]:
(B.T).shape

(3, 2)

In [13]:
np.dot(A,B.T)

array([[12, 18],
       [30, 45]])

#Using Pytorch

In [14]:
# dot product using one d array

import torch as py

A = py.tensor([1,2,3])

B = py.tensor([2,2,2])


py.dot(A,B)

tensor(12)

In [29]:
# dot product using 2 d array

import torch as py

A = py.tensor([[1,2,3],[4,5,6]])

B = py.tensor([[2,2,2],[3,3,3]])

# make a transposition of vector B for dot product

A.shape

torch.Size([2, 3])

In [30]:
(B.T).shape

torch.Size([3, 2])

In [18]:
py.dot(A,(B.T))

RuntimeError: ignored

In [33]:
py.matmul(A, (B.T))


tensor([[12, 18],
        [30, 45]])

#Using tensorflow

In [22]:
# dot product using one d array

import tensorflow as tf

A = tf.Variable([1,2,3])

B = tf.Variable([2,2,2])


tf.reduce_sum(tf.multiply(A,B))

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [23]:
# dot product using 2 d array

import tensorflow as tf

A = tf.Variable([[1,2,3],[4,5,6]])

B = tf.Variable([[2,2,2],[3,3,3]])

# make a transposition of vector B for dot product

A.shape

TensorShape([2, 3])

In [25]:
(tf.transpose(B)).shape

TensorShape([3, 2])

In [26]:
tf.reduce_sum(tf.multiply(A,B))

<tf.Tensor: shape=(), dtype=int32, numpy=57>