<a href="https://colab.research.google.com/github/darshank26/Linear_Algebra_for_ML/blob/main/13_Exercise_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. What is transpose of yT = [ [42, 4, 7, 99] , [ -99, -3, 17, 22 ] ]

In [2]:
import numpy as np

y = np.array([[42, 4, 7, 99] , [ -99, -3, 17, 22 ]] )

y

array([[ 42,   4,   7,  99],
       [-99,  -3,  17,  22]])

In [3]:
y.T

array([[ 42, -99],
       [  4,  -3],
       [  7,  17],
       [ 99,  22]])

2. What is Hadamard product of

[ [ 25, 10 ] , [-2 , 1 ] ] . [ [ -1 , 7 ] , [ 10, 8 ] ]

In [6]:
import numpy as np

x  = np.array([[ [ 25, 10 ] , [-2 , 1 ] ]] )
x

array([[[25, 10],
        [-2,  1]]])

In [5]:
y  = np.array([ [ -1 , 7 ] , [ 10, 8 ] ] )
y

array([[-1,  7],
       [10,  8]])

In [8]:
np.multiply(x,y)

array([[[-25,  70],
        [-20,   8]]])

3. What is dot product of

w = [-1,2,-2]

x = [5, 10, 0]

In [9]:
import numpy as np

w  = np.array([-1,2,-1] )
w

array([-1,  2, -1])

In [10]:
x  = np.array([5,10,0] )
x

array([ 5, 10,  0])

In [11]:
np.dot(w,x)

15