<a href="https://colab.research.google.com/github/darshank26/Linear_Algebra_for_ML/blob/main/15_matrix_multiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix Multiplication with vector



#using numpy

In [4]:
import numpy as np

A = np.array([[3,4],[5,6],[7,8]])

B = np.array([1,2])

np.dot(A,B)

array([11, 17, 23])

#using pytorch

In [5]:
import torch as py

A = py.tensor([[3,4],[5,6],[7,8]])

B = py.tensor([1,2])

py.matmul(A,B)

tensor([11, 17, 23])

#using tensorflow

In [6]:
import tensorflow as tf

A = tf.Variable([[3,4],[5,6],[7,8]])

B = tf.Variable([1,2])

tf.linalg.matvec(A,B)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([11, 17, 23], dtype=int32)>

#Matrix Multiplication with matrix



#using numpy

In [7]:
import numpy as np

A = np.array([[3,4],[5,6],[7,8]])

B = np.array([[1,9],[2,0]])

np.dot(A,B)

array([[11, 27],
       [17, 45],
       [23, 63]])

In [8]:
import torch as py

A = py.tensor([[3,4],[5,6],[7,8]])

B = py.tensor([[1,9],[2,0]])

py.matmul(A,B)

tensor([[11, 27],
        [17, 45],
        [23, 63]])

In [11]:
import tensorflow as tf

A = tf.Variable([[3,4],[5,6],[7,8]])

B = tf.Variable([[1,9],[2,0]])

tf.matmul(A,B)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 27],
       [17, 45],
       [23, 63]], dtype=int32)>