<a href="https://colab.research.google.com/github/darshank26/Linear_Algebra_for_ML/blob/main/16__Symmetric_matix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Symmetric matrix


Matrix is called Symmetric matric if its transpose is exactly the same as the given matrix

In [2]:
import numpy as np

A = np.array([[0,1,2],[1,7,8],[2,8,9]])

A

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [3]:
A.T

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [4]:
A == A.T

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])