<a href="https://colab.research.google.com/github/darshank26/Linear_Algebra_for_ML/blob/main/17_identity_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Identity Matrix

Matrix is called identity matrix if all of its diagonal elements is p, where p is whole number

If we multiply identity matrix with any vector then will get the same vector tensor


In [1]:
import numpy as np

x = np.array([[1,0,0],[0,1,0],[0,0,1]])

x

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [7]:
a = np.array([1,2,3])

a

array([1, 2, 3])

In [8]:
np.dot(x,a)

array([1, 2, 3])