<a href="https://colab.research.google.com/github/darshank26/Linear_Algebra_for_ML/blob/main/18_excercise_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Question one

import numpy as np

A = np.array([[0,1,2],[3,4,5],[6,7,8]])

B = np.array([-1,1,-2])

np.dot(A,B)

array([ -3,  -9, -15])

In [2]:
#Question two

import numpy as np

A = np.array([[1,0,0],[0,1,0],[0,0,1]])

B = np.array([-1,1,-2])

np.dot(A,B)

array([-1,  1, -2])

In [3]:
#Question three

import numpy as np

A = np.array([[0,1,2],[3,4,5],[6,7,8]])

B = np.array([[-1,0],[1,1],[-2,2]])

np.dot(A,B)


array([[ -3,   5],
       [ -9,  14],
       [-15,  23]])