<a href="https://colab.research.google.com/github/darshank26/Linear_Algebra_for_ML/blob/main/19_matrix_inversion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix inversion

In matrix if A.A<sup>-1</sup> = I

In [9]:
import numpy as np

A = np.array([[1,2],[3,4]])

A

array([[1, 2],
       [3, 4]])

In [10]:
x = np.linalg.inv(A)

x

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [12]:
np.dot(A,x)

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [15]:
import torch as py

A = py.tensor([[1,2],[3,4.]])

A

tensor([[1., 2.],
        [3., 4.]])

In [16]:
x = py.inverse(A)

x

tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])

In [17]:
py.matmul(A,x)

tensor([[1., 0.],
        [0., 1.]])

In [18]:
import tensorflow as tf

A = tf.Variable([[1,2],[3,4.]])

A

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [19]:
x = tf.linalg.inv(A)

x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-2.0000002 ,  1.0000001 ],
       [ 1.5000001 , -0.50000006]], dtype=float32)>

In [21]:
tf.matmul(A,x)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.0000000e+00,  0.0000000e+00],
       [-4.7683716e-07,  1.0000002e+00]], dtype=float32)>