<a href="https://colab.research.google.com/github/darshank26/Linear_Algebra_for_ML/blob/main/19_matrix_inversion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix inversion

In matrix if A.A<sup>-1</sup> = I

In [9]:
import numpy as np

A = np.array([[1,2],[3,4]])

A

array([[1, 2],
       [3, 4]])

In [10]:
x = np.linalg.inv(A)

x

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [12]:
np.dot(A,x)

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])